package:
  name: knossos_utils
  version: 0.1

source:
  path: ./

requirements:
  build:
    - python
    - setuptools >=20.6
    - cython >=0.23
    - h5py >=2.5
    - imageio
    - numpy >=1.10
    - scipy >=0.17.1
    - python-snappy >=0.5
    - gcc >=4.8
    - networkx >=1.11
    - requests >=2.12

  run:
    - python
    - cython >=0.23
    - h5py >=2.5
    - imageio
    - numpy >=1.10
    - scipy >=0.17.1
    - python-snappy >=0.5
    - networkx >=1.11
    - requests >=2.12
    # - skeletopyze (add, when channels can be specified)

build:
  script: $PYTHON -m pip install .

about:
  home: https://github.com/knossos-project/knossos_python_tools
  license: GPLv2
  license_file: LICENSE
